config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :new, :create, :show,] do
    resources :reviews, only: [:new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
  validates :category, presence: true, inclusion: { in: CATEGORIES }
  validates :name, presence: true
  validates :phone_number, presence: true
  validates :address, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: :true
  RATES = [0, 1, 2, 3, 4, 5]
  validates :rating, presence: true, inclusion: { in: RATES }, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @reviews = @restaurant.reviews
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  # def review_params
  #   params.require(:review).permit(:content, :rating)
  # end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    # we need `restaurant_id` to associate review with corresponding restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    @review.save
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <h1 class="w-50 mx-auto text-center">All the restaurants</h1>
    <div class="card" style="width: 700px; margin-top: 80px;">
      <% @restaurants.each do |restaurant| %>
        <div class="card-body">
          <h5 class="card-title"><%= link_to restaurant.name, restaurant_path(restaurant) %></h5>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<h1>Add a new restaurant:</h1>
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name, error: 'The name is mandatory, please specify one' %>
  <%= f.input :address, error: 'The address is mandatory, please specify one'  %>
  <%= f.input :phone_number, as: :string, placeholder: '01 20 20 20 20', error: 'The phone number is mandatory, please specify one'   %>
  <%= f.input :category, as: :select, collection: ["chinese", "italian", "japanese", "french", "belgian"], prompt: 'Select a category', error: 'The category is mandatory, please specify one'  %>
  <%= f.submit "Add the restaurant", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="card" style="width: 700px; margin-top: 50px;">
      <div class="card-body">
        <h5 class="card-title"><%= @restaurant.name %></h5>
        <p class="card-text"><%= @restaurant.address %></p>
        <%= link_to 'Back to the restaurants', restaurants_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>

  <div class="row justify-content-md-center">
    <div class="card" style="width: 700px; margin-top: 50px;">
      <div class="card-body">
        <h6 class="card-title">Reviews of <%= @restaurant.name %>:</h6>
        <ul class="list-group">
          <% @reviews.each do |review| %>
           <li class="list-group-item"><%= review.content %>  / <%= review.rating %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
<br>
<br>
<h1>Add a review for the @restaurant.name:</h1>
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :content, error: 'Please write a review'  %>
  <%= f.input :rating, as: :select, collection: [0, 1, 2, 3, 4, 5], prompt: 'Your rating', error: 'A rating please'  %>
  <%= f.submit "Add your review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/new.html.erb
<h1>Add a review for the @restaurant.name:</h1>
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :content, error: 'Please write a review'  %>
  <%= f.input :rating, as: :select, collection: [0, 1, 2, 3, 4, 5], prompt: 'Your rating', error: 'A rating please'  %>
  <%= f.submit "Add your review", class: "btn btn-primary" %>
<% end %>